import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter, Work_Sans } from 'next/font/google';
import './globals.css';
import ClientInit from './client-init';// u slucaju da zelimo da se uklanja iz localStorage-a svaki put kad se app load-uje

const inter = Inter({
  subsets: ['latin'],
});
const workSans = Work_Sans({
  subsets: ['latin'],
});
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
